/*
Warm up

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/
var  sum = []
var evenTotal = 0
for(var i = 0; i < 10; i++){

  if(i === 0){
     sum[0] = i
     console.log(sum[0]);
  }else if (i === 1) {
    sum[1] = i
    console.log(sum[1]);
  } else if (i === 2) {
    sum[2] = sum[0] + sum[1]
    console.log(sum[2]);
  }else {
    sum[i] = sum[i - 1] + sum[i - 2]
    console.log(sum[i]);
    if((sum[i]%2) === 0)
    {
      evenTotal = evenTotal + sum[i];
    }
  }
}
console.log("Even numbers total: " + evenTotal);
